spring:
  datasource:
    url: jdbc:dm://localhost:5236?schema=MY_USER
    username: MY_USER
    password: MY_USER
    driver-class-name: dm.jdbc.driver.DmDriver
  redis:
    port: 6379
    host: localhost



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 9999

logging:
  level:
    com.wzh: debug
